services:
  postgres:
    image: postgres:11.13
    expose:
      - '${PGPORT}'
    ports:
      - '${PGPORT}:${PGPORT}'
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PORT=${PGPORT}

    networks:
      - teamstarter
    command:
      [
        'postgres',
        '-c',
        'fsync=off',
        '-c',
        'synchronous_commit=off',
        '-c',
        'full_page_writes=off',
        '-p',
        '${PGPORT}',
      ]
networks:
  teamstarter:
    driver: bridge
